version: "3.9"

services:
  web:
    build: .
    container_name: automail-web
    ports:
      - "5000:5000"
    environment:
      - PYTHONUNBUFFERED=1
      - MONGO_URI=mongodb://mongodb:27017/
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - rabbitmq

  worker:
    build: .
    container_name: automail-worker
    command: python3 worker/worker.py
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
      - RABBITMQ_HOST=rabbitmq
    volumes:
      - .:/app
    depends_on:
      - mongodb
      - rabbitmq

  mongodb:
    image: mongo:5.0
    container_name: automail-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

  rabbitmq:
    image: rabbitmq:3-management
    container_name: automail-rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:

